name: Primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  Compilar:
    # criar maquina virtual par ausar no pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Fazer o git clone
        uses: actions/checkout@v4

      - name: Executando primeiro comando
        run: echo "Hello, world!"

      - name: Executando dois ou mais comandos
        run: |
          ls -l
          echo "Fim do PROCESSO"

  deploy:
    needs : Compilar
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        
  Docker:
    needs: Compilar
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v4.6.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_SENHA}}
    
